name: 'Environment Setup'
description: 'Set up the CI environment'
runs:
  using: "composite"
  steps:
    - name: Create required configs
      run: |
        cp configs.sample.js configs.js

    - name: Install Node modules
      run: |
        yarn install
        yarn compile:vue-routes
        yarn webpack:development
        yarn add pa11y

    - name: Install Deno
      uses: denolib/setup-deno@v2
