name: 'Environment Setup'
description: 'Set up the CI environment'
runs:
  using: "composite"
  steps:
    - name: Create required configs
      shell: bash
      run: |
        cp configs.sample.js configs.js

    - name: Install Node modules
      shell: bash
      run: |
        yarn install
        yarn compile:vue-routes
        yarn webpack:development
        yarn add pa11y
