name: Master

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  # Run all kinds of tests
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create required configs
        run: |
          cp configs.sample.js configs.js

      - name: Install Node modules
        run: |
          yarn install
          yarn compile:vue-routes
          yarn webpack:development
          yarn add pa11y

      - name: Install Deno
        uses: denolib/setup-deno@v2

      - name: Build docker image
        run: |
          yarn docker:build-production

      - name: Start local server
        run: |
          yarn server &
          sleep 10

      - name: Tets: Accessibility
        run: |
          node_modules/.bin/pa11y --ignore "WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail" http://localhost:1445
          node_modules/.bin/pa11y --ignore "WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail" http://localhost:1445/drash

      - name: Tests: Integration
        run: |
          deno test -A tests/integration

      - name: Tests: Pre-release
        run: |
          node console/update_module_versions.js \
            --module drash \
            --version release-v1.0.0

      - name: Tests: Docker
        run: |
          docker run --detach --rm --name website --publish 1446:1445 drashland-website
          deno test -A tests/docker

  # Lint roll
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create configs.js
        run: |
          cp configs.sample.js configs.js

      - name: Install Deno
        uses: denolib/setup-deno@v2

      - name: Formatter
        # for dev: deno fmt --ignore=assets,console/compile_vue_routes.js,configs.webpack.js,console/update_module_versions.js,configs.node.js,ecosystem.config.sample.js,node_modules,configs.js
        run: deno fmt --ignore=assets,console/compile_vue_routes.js,configs.webpack.js,console/update_module_versions.js,configs.node.js,ecosystem.config.sample.js

      - name: Linter
      # command to use in dev (if you've ran builds and created compiled files): deno lint --unstable --ignore=assets,console/compile_vue_routes.js,configs.webpack.js,console/update_module_versions.js,configs.js,configs.node.js,ecosystem.config.sample.js,configs.webpack.common.js,configs.webpack.development.js,ecosystem.config.js,node_modules,src/modules/drash-v1.x/router.js,src/modules/dmm-v1.x/router.js,src/modules/rhum-v1.x/router.js,src/modules/wocket-v0.x/router.js,src/modules/sinco-v1.x/router.js,configs.webpack.production.js,src/modules/drash-v1.x/app.js,src/modules/sinco-v2.x/router.js
        run: deno lint --unstable --ignore=assets,console/compile_vue_routes.js,configs.webpack.js,configs.webpack.production.js,console/update_module_versions.js,configs.js,configs.node.js,ecosystem.config.sample.js,configs.webpack.common.js,configs.webpack.development.js,configs.production.webpack.js,src/modules/drash-v1.x/app.js,src/modules/drash-v1.x/router.js,src/modules/dmm-v1.x/router.js,src/modules/rhum-v1.x/router.js,src/modules/wocket-v0.x/router.js,src/modules/sinco-v1.x/router.js,src/modules/sinco-v2.x/router.js,src/modules/line-v1.x/router.js,src/modules/line-v1.x/router.js
