name: Master

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  # Run all kinds of tests
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create required configs
        run: |
          cp configs.sample.js configs.js

      - name: Install Node modules
        run: |
          yarn install
          yarn compile:vue-routes
          yarn webpack:development
          yarn add pa11y

      - name: Install Deno
        uses: denolib/setup-deno@v2

      - name: Build docker image
        run: |
          yarn docker:build-production

      - name: Start local server
        run: |
          yarn server &
          sleep 10

      - name: Run accessibility tests
        run: |
          node_modules/.bin/pa11y --ignore "WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail" http://localhost:1445
          node_modules/.bin/pa11y --ignore "WCAG2AA.Principle1.Guideline1_4.1_4_3.G18.Fail" http://localhost:1445/drash

      - name: Run integration tests
        run: |
          deno test -A tests/integration

      - name: Run pre-release workflow
        run: |
          node console/update_module_versions.js \
            --module drash \
            --version release-v1.0.0

      - name: Run Docker tests
        run: |
          docker run --detach --rm --name website --publish 1446:1445 drashland-website
          deno test -A tests/docker

  # Lint roll
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@v2

      - name: Check formatting
        run: |
          deno fmt app.ts server.ts src/modules tests --check

      - name: Lint the codebase
        run: |
          deno lint --unstable src/modules tests
